---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nwengine/public_html/nwesadmin/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/*.php
    - /bin/chmod 755 $DEPLOYPATH/*/
    - echo "Deployment completed successfully!"
